name: ðŸš€ Publish to Chrome Web Store

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    name: Upload & Publish to Chrome Web Store
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload & Publish to Chrome Web Store
        uses: Klemensas/chrome-extension-upload-action@master
        with:
          app-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          file-name: ./dist/indeed-quicksearch.zip
          publish: true
